export * from "./Home";
export * from "./Login";
export * from "./Register";
export * from "./Profile";
export * from "./Appointments";
export * from "./Gallery";
export * from "./ArtistPortfolio";
export * from "./Admin";
export * from "./Landing";
